-- PostgreSQL schema for 外観検査記録照会.
-- PostgreSQL 側の物理名は英語表記に統一する。

CREATE TABLE IF NOT EXISTS appearance_records (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    inspector_id varchar(4),
    production_lot_id varchar(7),
    process_no varchar(2),
    inspection_date timestamp,
    inspection_time timestamp,
    part_number varchar(30),
    part_name varchar(30),
    customer_name varchar(25),
    quantity integer,
    updated_flag varchar(1),
    excluded_from_summary boolean NOT NULL DEFAULT false
);

CREATE TABLE IF NOT EXISTS appearance_summary (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    inspector_id varchar(4),
    inspection_date timestamp,
    production_lot_id varchar(7),
    part_number varchar(30),
    part_name varchar(30),
    process_no varchar(2),
    quantity integer,
    work_minutes integer,
    excluded_from_summary boolean NOT NULL DEFAULT false
);

CREATE TABLE IF NOT EXISTS process_master (
    process_no integer,
    process_name varchar(10)
);

CREATE TABLE IF NOT EXISTS numeric_inspector_master (
    inspector_id varchar(4),
    inspector_name varchar(5),
    category varchar(5),
    visible boolean NOT NULL DEFAULT false
);

CREATE TABLE IF NOT EXISTS numeric_inspection_records (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    recorded_at timestamp,
    production_lot_id varchar(7),
    inspector_id varchar(4),
    process_name varchar(30),
    machine_no varchar(5)
);

CREATE TABLE IF NOT EXISTS inspector_master (
    inspector_id varchar(4),
    inspector_name varchar(10),
    display_order varchar(3),
    team varchar(1),
    kana varchar(1)
);

CREATE TABLE IF NOT EXISTS product_catalog (
    production_lot_id varchar(7),
    machine_no varchar(5),
    part_number varchar(30),
    part_name varchar(30),
    customer_name varchar(30),
    instruction_date timestamp,
    quantity integer
);

CREATE OR REPLACE VIEW production_lot_summary AS
SELECT
    production_lot_id,
    process_no,
    part_number,
    part_name,
    SUM(COALESCE(quantity, 0)) AS quantity,
    SUM(COALESCE(work_minutes, 0)) AS total_work_minutes
FROM appearance_summary
GROUP BY production_lot_id, process_no, part_number, part_name;

CREATE OR REPLACE VIEW production_lot_aggregate AS
SELECT
    production_lot_id,
    process_no,
    part_number,
    part_name,
    quantity,
    total_work_minutes
FROM production_lot_summary;
