-- PostgreSQL schema for appearance_inspection_db.
-- Physical names follow the migration mapping in docs/appearance_inspection_db.

CREATE TABLE IF NOT EXISTS excel_product_slip_history (
    production_lot_id varchar(7),
    machine_no varchar(5),
    product_code varchar(30),
    product_name varchar(30),
    customer varchar(30),
    material varchar(50),
    material_lot_no varchar(30),
    quantity integer,
    remarks varchar(50),
    instruction_date timestamp,
    completion_flag varchar(1)
);

CREATE TABLE IF NOT EXISTS check_sheet_list (
    no integer,
    customer varchar(25),
    file_no varchar(10)
);

CREATE TABLE IF NOT EXISTS defect_information (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    production_lot_id varchar(7),
    product_code varchar(30),
    instruction_date timestamp,
    machine_no varchar(5),
    inspector_1 varchar(6),
    inspector_2 varchar(6),
    inspector_3 varchar(6),
    inspector_4 varchar(6),
    inspector_5 varchar(20),
    time_value integer,
    quantity integer,
    total_defect_count integer,
    defect_rate double precision,
    appearance_scratch integer,
    dent integer,
    cutting_chip integer,
    mushire integer,
    oversized_hole integer,
    undersized_hole integer,
    hole_scratch integer,
    burr integer,
    short_length integer,
    rough_surface integer,
    rust integer,
    blur integer,
    turning_mark integer,
    stain integer,
    plating integer,
    dropped integer,
    swelling integer,
    crush integer,
    bump integer,
    step integer,
    barrel_stone integer,
    diameter_plus integer,
    diameter_minus integer,
    gauge integer,
    foreign_matter integer,
    shape_defect integer,
    abrasion integer,
    discoloration_stain integer,
    material_scratch integer,
    dust integer,
    other integer,
    other_detail varchar(10)
);

CREATE TABLE IF NOT EXISTS appearance_inspection_records (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    inspector_id varchar(4),
    production_lot_id varchar(7),
    process_no varchar(2),
    inspection_date timestamp,
    time_at timestamp,
    product_code varchar(30),
    product_name varchar(30),
    customer varchar(25),
    quantity integer,
    update_flag varchar(1),
    aggregation_exclusion_flag boolean NOT NULL DEFAULT false
);

CREATE TABLE IF NOT EXISTS appearance_inspection_record_archives (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    inspector_id varchar(4),
    production_lot_id varchar(7),
    process_no varchar(2),
    inspection_date timestamp,
    time_at timestamp,
    product_code varchar(30),
    product_name varchar(30),
    customer varchar(25),
    quantity integer,
    update_flag varchar(1),
    aggregation_exclusion_flag boolean NOT NULL DEFAULT false
);

CREATE TABLE IF NOT EXISTS appearance_inspection_summaries (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    inspector_id varchar(4),
    inspection_date timestamp,
    production_lot_id varchar(7),
    product_code varchar(30),
    product_name varchar(30),
    process_no varchar(2),
    quantity integer,
    work_time integer,
    aggregation_exclusion_flag boolean NOT NULL DEFAULT false
);

CREATE TABLE IF NOT EXISTS appearance_inspection_summary_archives (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    inspector_id varchar(4),
    inspection_date timestamp,
    production_lot_id varchar(7),
    product_code varchar(30),
    product_name varchar(30),
    process_no varchar(2),
    quantity integer,
    work_time integer,
    aggregation_exclusion_flag boolean NOT NULL DEFAULT false
);

CREATE TABLE IF NOT EXISTS process_master (
    process_no integer,
    process_name varchar(10)
);

CREATE TABLE IF NOT EXISTS numeric_inspector_master (
    inspector_id varchar(4),
    inspector_name varchar(5),
    category varchar(5),
    display_flag boolean NOT NULL DEFAULT false
);

CREATE TABLE IF NOT EXISTS numeric_inspection_records (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    inspected_at timestamp,
    production_lot_id varchar(7),
    inspector_id varchar(4),
    process_name varchar(30),
    machine_no varchar(5)
);

CREATE TABLE IF NOT EXISTS inspection_in_progress (
    inspector_id varchar(4),
    production_lot_id varchar(7),
    time_at timestamp,
    display_flag varchar(1)
);

CREATE TABLE IF NOT EXISTS inspector_master (
    inspector_id varchar(4),
    inspector_name varchar(10),
    display_position varchar(3),
    team varchar(1),
    furigana varchar(1)
);

CREATE TABLE IF NOT EXISTS inspection_person_master (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    inspector_name varchar(6),
    furigana varchar(1)
);
